import { Repository } from 'typeorm';
import { legalConfig } from '../../config/legal.config';
import { LegalDocument, LegalDocumentType } from '../../entities/legal-document.entity';

export type LegalDocumentSeed = {
  documentType: LegalDocumentType;
  version: string;
  title: string;
  content: string;
  jurisdiction?: string;
};

const c = legalConfig();
const configured = (value: string | undefined, placeholder: string) => value || placeholder;
const header = (scope: string) => `Version: 1.0\nEffective date: [EFFECTIVE_DATE]\nLast updated: [LAST_UPDATED]\nApplicable scope: ${scope}\n\nContact: ${configured(c.privacyEmail, '[PRIVACY_EMAIL]')}\nLegal contact: ${configured(c.legalEmail, '[LEGAL_EMAIL]')}\nEntity: ${configured(c.entityName, '[LEGAL_ENTITY_NAME]')}\nAddress: ${configured(c.entityAddress, '[REGISTERED_ADDRESS]')}\n\nThis is a technical first-draft framework and is not legal advice. It is not a claim that Sentira is certified or compliant with every jurisdiction. Obtain jurisdiction-specific legal review before publication.`;

export const LEGAL_DOCUMENTS: LegalDocumentSeed[] = [
  { documentType: 'TERMS_OF_SERVICE', version: '1.0', title: 'Sentira Terms of Service', content: `${header('Service users and customer organizations')}\n\n1. Acceptance. By creating an account or using the service where legally permitted, you agree to these Terms. Organization administrators may bind their organization within their authority.\n\n2. Accounts and access. Keep registration information accurate, protect passwords, API keys and connector credentials, and ensure authorized users follow least-privilege access and RBAC requirements. You are responsible for activity under your account.\n\n3. Customer responsibility. The customer decides why and how its cameras, video, audio, evidence and AI alerts are used. The customer is responsible for lawful deployment, notices, workplace monitoring, recording and retention rules, data subject requests, and authorization to connect each device. Sentira does not make a CCTV deployment lawful by providing the service.\n\n4. Service and AI limitations. Sentira provides monitoring and video intelligence tooling. Detections and alerts are probabilistic and can be wrong. Review important events before consequential action. Sentira does not make final employment, legal, disciplinary or security decisions for customers.\n\n5. Customer content and security. You retain responsibility for customer content and must not upload unlawful material or credentials in ordinary text fields. Sentira applies reasonable technical controls, but no service is risk-free.\n\n6. Acceptable use, availability, third parties, billing, trials, intellectual property, suspension, termination, deletion, disclaimers, liability and indemnification. These topics must be finalized for the commercial plan and customer relationship with legal counsel.\n\n7. Governing law and disputes. [GOVERNING_LAW] and [JURISDICTION] are placeholders and must not be published as final legal terms until confirmed. Changes will be versioned; material changes may require renewed acceptance.` },
  { documentType: 'PRIVACY_POLICY', version: '1.0', title: 'Sentira Privacy Policy', content: `${header('Visitors, account users, customer organizations and people represented in customer data')}\n\n1. Controller and roles. ${c.entityName} at ${c.entityAddress} is the configured legal contact. Whether Sentira is a controller, processor, joint controller or another role depends on the processing activity and agreement. Customers generally determine the purposes and means of their CCTV use.\n\n2. Information. We may process account data such as name, email, organization and role; technical data such as IP address, device, logs, session identifiers, timestamps and security events; service data such as camera configuration, sites, zones, rules, alerts and evidence metadata; and customer-provided video that may contain faces, people, vehicles, plates, voices, behavior or location information depending on configuration and source.\n\n3. AI processing. Computer vision may detect objects, people or vehicles, evaluate zones and rules, create alerts, and extract event metadata. We do not claim facial recognition, biometric identification, emotion recognition or biometric categorization unless a specific documented feature exists. AI output can be inaccurate and should be reviewed by a human for important decisions.\n\n4. Purposes and legal bases. Purposes can include account and contract administration, service delivery, security, support, diagnostics, billing, compliance and product improvement. Potential legal bases include consent, contract, legal obligation, legitimate interests, vital interests or public task. No basis is automatically asserted for every customer or jurisdiction.\n\n5. Rights. Where applicable, people may have access, rectification, erasure, restriction, portability, objection, withdrawal of consent and rights relating to automated decision-making, plus a right to complain to a supervisory authority. Availability depends on law, role, purpose and legal basis. Contact ${c.privacyEmail}; DPO contact is ${c.dpoEmail}.\n\n6. Retention, transfers and security. Retention depends on account, security, billing, configuration, video, evidence, support and legal requirements. Customers should configure CCTV retention for their own obligations. Data may be processed across hosting, backup, support and subprocessor locations; the applicable transfer mechanism must be documented rather than assumed.\n\n7. Children, changes and contact. Do not use the service for unlawful surveillance or submit unnecessary sensitive data. This document is versioned and may be updated after review.` },
  { documentType: 'COOKIE_POLICY', version: '1.0', title: 'Sentira Cookie Policy', content: `${header('Website and application visitors')}\n\nSentira uses cookies and similar storage for strictly necessary authentication, security, session management, load balancing, consent storage and core functionality. Optional categories may include preferences, analytics, marketing or third-party content only when actually enabled and where permitted.\n\nOptional categories are not preselected. Visitors can accept all, reject optional categories, manage preferences, or later withdraw or change their choice. Optional scripts must not initialize before the required consent decision. Consent records contain category choices, policy versions, source and timestamps; raw cookie values are not stored as consent data.\n\nThe actual technologies, providers, retention and locations must be maintained in the subprocessor and service inventory. Contact ${c.privacyEmail} with questions.` },
  { documentType: 'ACCEPTABLE_USE_POLICY', version: '1.0', title: 'Sentira Acceptable Use Policy', content: `${header('All service users and customer organizations')}\n\nYou may connect only cameras and systems you are authorized to access. You must not use Sentira for illegal surveillance, credential theft, stalking, harassment, unlawful biometric processing, unauthorized monitoring, bypassing security, malicious alerts, API abuse, malware, attacks against infrastructure, or unlawful collection of personal data.\n\nDo not expose cameras directly to the public internet unnecessarily. Do not put camera credentials, API secrets or private video URLs in frontend code, logs or support requests. Customers must assess employee monitoring, signage, audio recording, biometric features and local surveillance obligations. We may restrict or suspend misuse after appropriate review.` },
  { documentType: 'AI_TRANSPARENCY_NOTICE', version: '1.0', title: 'Sentira AI and Video Analytics Notice', content: `${header('AI and computer-vision features')}\n\nSentira may use automated computer vision for object and person detection, vehicle detection, zones, rules, event metadata, alerts and evidence generation. Accuracy can be affected by lighting, camera angle, resolution, weather, occlusion, network quality and model limitations. An alert is not proof of wrongdoing.\n\nRecommended workflow: AI detection -> alert -> human review -> customer decision. Customers must configure rules appropriately and review important events. Sentira does not claim that every deployment has the same regulatory classification under the EU AI Act or other law. The applicable system, purpose, provider/deployer relationship, limitations, risks, oversight and jurisdiction should be documented for each use.\n\nBiometric identification, facial recognition, emotion recognition and biometric categorization are not claimed unless explicitly implemented and documented. If unsupported, this capability is not currently supported.` },
  { documentType: 'VIDEO_SURVEILLANCE_NOTICE', version: '1.0', title: 'CCTV and Video Surveillance Responsibility Notice', content: `${header('Customer deployment of cameras, recorders and video')}\n\nThe customer is responsible for lawful camera placement, signage, informing employees and visitors where required, lawful basis, workplace and labor rules, retention, access control, data subject responses, surveillance and recording laws, biometric and audio rules, and authorization to access connected systems.\n\nIf employees or workers are monitored, obtain appropriate employment, labor and privacy advice. Audio recording can trigger additional laws; configure and disclose it only where supported and lawful. A customer subject in video is not assumed to have a Sentira account. Sentira technology does not make a deployment lawful and does not determine the customer's legal basis.` },
  { documentType: 'DATA_PROCESSING_AGREEMENT', version: '1.0', title: 'Sentira Data Processing Agreement Framework', content: `${header('Business customers requiring a processing agreement')}\n\nThis framework is not a signed DPA. The parties must establish their roles for each processing activity. Topics for legal review include documented instructions, confidentiality, security, subprocessors, data subject request assistance, breach assistance, deletion or return, audit information, international transfers, transfer mechanisms such as SCCs or adequacy decisions, and duration and subject matter.\n\nThe customer remains responsible for lawful instructions and permissions for customer video. Sentira should process only the agreed data and purpose, subject to the applicable service relationship and final contract.` },
  { documentType: 'SUBPROCESSOR_LIST', version: '1.0', title: 'Sentira Subprocessor List', content: `${header('Current service providers')}\n\nOnly actual providers used by the deployed Sentira environment may be listed here. For each provider record: provider name, service, processing purpose, data categories, processing location, transfer mechanism and privacy URL. Do not invent vendors. The operator must maintain this list with change notice and legal review before publication.` },
  { documentType: 'DATA_RETENTION_POLICY', version: '1.0', title: 'Sentira Data Retention Policy', content: `${header('Retention of platform and customer data')}\n\nRetention varies by account data, security logs, billing records, customer configuration, CCTV footage, evidence clips, alerts, support records and legal requirements. Customers should configure video and evidence retention according to their own legal and business requirements. Sentira should minimize copied video, restrict evidence access, use tenant isolation, log sensitive access and delete data when the configured period and applicable holds permit. No universal CCTV retention period is promised.` },
  { documentType: 'SECURITY_POLICY', version: '1.0', title: 'Sentira Security and Trust Statement', content: `${header('Security practices and limitations')}\n\nSentira is designed around authentication, authorization, RBAC, tenant isolation, audit logging, credential protection, secrets management, backups, monitoring, incident response and vulnerability management. Evidence should use private storage and expiring access where supported. Customers must protect accounts, connectors and network paths. This statement does not claim ISO 27001, SOC 2, PCI DSS, HIPAA or any other certification.` },
  { documentType: 'ACCOUNT_DELETION_POLICY', version: '1.0', title: 'Sentira Account Deletion Policy', content: `${header('User, organization and customer data deletion')}\n\nDeletion distinguishes a user, organization, camera configuration, evidence, video, connector and legally required record. Requests are reviewed for authority, dependencies, active legal holds, security needs and retention obligations. A privacy request is not an automatic deletion command. Deletion and return behavior should be confirmed in the customer contract and may require administrator action.` },
  { documentType: 'SECURITY_INCIDENT_POLICY', version: '1.0', title: 'Sentira Security Incident and Breach Policy', content: `${header('Internal incident response')}\n\nThe operational process is: detect and triage; contain; investigate; assess risk; decide on customer and regulatory notifications; communicate where required; recover; and complete a post-incident review. Notification timing depends on applicable law, facts, role and verified contacts. This framework does not promise a universal notification deadline. Never include passwords, camera credentials, API secrets or unnecessary sensitive video in incident notes.` },
];

export async function seedLegalDocuments(repository: Repository<LegalDocument>) {
  for (const document of LEGAL_DOCUMENTS) {
    const existing = await repository.findOne({ where: { documentType: document.documentType, version: document.version } });
    if (!existing) {
      await repository.save({ ...document, status: 'DRAFT', jurisdiction: document.jurisdiction, language: 'en', effectiveAt: null, publishedAt: null });
    }
  }
  return LEGAL_DOCUMENTS.length;
}
