"""Reconcile the FastAPI model schema without changing existing data.

Revision ID: 303fea8f86b8
Revises: phase21_merge_20260910
Create Date: 2026-09-10 09:52:58.110472

This migration intentionally does not replay autogenerated schema changes.
The production database already contains the application tables, and later
migrations own the remaining invoice, HR, and ERP schema changes.
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "303fea8f86b8"
down_revision = "20260909_fresh_schema_bootstrap"
branch_labels = None
depends_on = None


REQUIRED_TABLES = (
    "account",
    "api_keys",
    "approval_requests",
    "assets",
    "attendance_record",
    "coupons",
    "customers",
    "department",
    "depreciation_entry",
    "employee",
    "entity",
    "expenses",
    "invoice",
    "invoice_line",
    "invoice_sequence",
    "items",
    "journal_entry",
    "journal_line",
    "leads",
    "notifications",
    "opportunities",
    "organizations",
    "otps",
    "payment",
    "payslip",
    "performance_review",
    "purchase_order_line_items",
    "purchase_orders",
    "refresh_tokens",
    "stock_record",
    "stock_transaction",
    "users",
    "vendors",
    "warehouse",
)


def _verify_required_tables(inspector):
    """Fail rather than reconstructing a missing production table."""
    existing_tables = set(inspector.get_table_names())
    missing_tables = sorted(set(REQUIRED_TABLES) - existing_tables)
    if missing_tables:
        raise RuntimeError(
            "303fea8f86b8 requires existing application tables; missing: "
            + ", ".join(missing_tables)
        )


def _verify_notification_preferences(inspector):
    """Validate an existing table without altering or recreating it."""
    required_columns = {
        "user_id": sa.Integer,
        "email_enabled": sa.Boolean,
        "in_app_enabled": sa.Boolean,
        "digest_enabled": sa.Boolean,
    }
    columns = {
        column["name"]: column
        for column in inspector.get_columns("notification_preferences")
    }
    missing_columns = sorted(set(required_columns) - set(columns))
    if missing_columns:
        raise RuntimeError(
            "303fea8f86b8 found notification_preferences without required columns: "
            + ", ".join(missing_columns)
        )

    incorrect_types = sorted(
        column_name
        for column_name, expected_type in required_columns.items()
        if not isinstance(columns[column_name]["type"], expected_type)
    )
    if incorrect_types:
        raise RuntimeError(
            "303fea8f86b8 found notification_preferences columns with incorrect types: "
            + ", ".join(incorrect_types)
        )

    primary_key = inspector.get_pk_constraint("notification_preferences")
    primary_key_columns = primary_key.get("constrained_columns") or []
    if primary_key_columns != ["user_id"]:
        raise RuntimeError(
            "303fea8f86b8 requires notification_preferences primary key "
            "to be exactly (user_id); found "
            + repr(primary_key_columns)
        )

    foreign_keys = inspector.get_foreign_keys("notification_preferences")
    has_users_foreign_key = any(
        foreign_key.get("constrained_columns") == ["user_id"]
        and foreign_key.get("referred_table") == "users"
        and foreign_key.get("referred_columns") == ["id"]
        for foreign_key in foreign_keys
    )
    if not has_users_foreign_key:
        raise RuntimeError(
            "303fea8f86b8 requires notification_preferences.user_id to reference users.id"
        )


def upgrade():
    """Verify the live schema and create only the missing model table."""
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    # Existing application tables are a prerequisite. No missing table is
    # silently recreated because doing so could mask an incorrect database.
    _verify_required_tables(inspector)

    existing_tables = set(inspector.get_table_names())
    if "notification_preferences" not in existing_tables:
        # This is the only table creation in this migration. Its primary key
        # is the model's user_id, not an autogenerated id column.
        op.create_table(
            "notification_preferences",
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("email_enabled", sa.Boolean(), nullable=True),
            sa.Column("in_app_enabled", sa.Boolean(), nullable=True),
            sa.Column("digest_enabled", sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("user_id"),
        )
    else:
        _verify_notification_preferences(inspector)


def downgrade():
    raise RuntimeError(
        "Downgrade disabled for 303fea8f86b8 reconciliation migration; "
        "use a reviewed forward migration for production schema changes."
    )
