"""add user profile and auth fields

Revision ID: 358f784f255a
Revises: 2aa562de3542
Create Date: 2025-12-12 06:24:52.429312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358f784f255a'
down_revision = '2aa562de3542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('designation', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('role')
        batch_op.drop_column('timezone')
        batch_op.drop_column('department')
        batch_op.drop_column('designation')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('currency')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
