"""add invoice sequence model

Revision ID: 76d2578a7a97
Revises: 358f784f255a
Create Date: 2025-12-13 03:57:07.556626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d2578a7a97'
down_revision = '358f784f255a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    if not insp.has_table('invoice_sequence'):
        op.create_table('invoice_sequence',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('last_number', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('year')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_sequence')
    # ### end Alembic commands ###
