import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787836670863 implements MigrationInterface {
    name = 'InitialSchema1787836670863'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "legalName" character varying(255), "status" character varying(50) NOT NULL DEFAULT 'active', "plan" character varying(32) NOT NULL DEFAULT 'FREE', "cameraLimit" integer NOT NULL DEFAULT '3', "retentionDays" integer NOT NULL DEFAULT '30', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "name" character varying(255) NOT NULL, "address" character varying(500), "timezone" character varying(50) NOT NULL DEFAULT 'UTC', "status" character varying(50) NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4f5eccb1dfde10c9170502595a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_201abf1417c53525146ebf0e8f" ON "sites" ("organizationId", "name") `);
        await queryRunner.query(`CREATE TABLE "cameras" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "siteId" uuid NOT NULL, "name" character varying(255) NOT NULL, "location" character varying(255), "streamUrl" text NOT NULL, "username" character varying(255), "passwordEncrypted" text, "protocol" character varying(50) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'offline', "resolution" character varying(100), "fps" integer NOT NULL DEFAULT '30', "lastHeartbeatAt" TIMESTAMP, "aiProcessingStatus" character varying(50) NOT NULL DEFAULT 'idle', "isEnabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_88b40b9817f9f422121f861e1e8" PRIMARY KEY ("id")); COMMENT ON COLUMN "cameras"."streamUrl" IS 'RTSP stream URL without credentials'; COMMENT ON COLUMN "cameras"."passwordEncrypted" IS 'Encrypted password'`);
        await queryRunner.query(`CREATE INDEX "IDX_dcf3a964d6fb0f584a80d51efb" ON "cameras" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_123f593d4c541d445ec520f24b" ON "cameras" ("organizationId", "siteId", "name") `);
        await queryRunner.query(`CREATE TABLE "zones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "cameraId" uuid NOT NULL, "name" character varying(255) NOT NULL, "zoneType" character varying(100) NOT NULL, "geometryJson" jsonb NOT NULL, "coordinatesJson" jsonb, "isEnabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_880484a43ca311707b05895bd4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f57d88e700fad5b0e232721d28" ON "zones" ("organizationId", "cameraId") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid, "name" character varying(100) NOT NULL, "description" character varying(500), "permissions" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d27a5e69fb41256abed347a85e" ON "roles" ("organizationId", "name") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "email" character varying(255) NOT NULL, "passwordHash" character varying(255) NOT NULL, "firstName" character varying(100), "lastName" character varying(100), "roleId" uuid NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'active', "lastLoginAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddfb7904324cdba38d3c73de93" ON "users" ("organizationId", "email") `);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "refreshTokenHash" character varying(255) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revokedAt" TIMESTAMP WITH TIME ZONE, "userAgent" character varying(255), "ipAddress" character varying(64), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_83264d35a590615280397a856c" ON "user_sessions" ("userId", "revokedAt") `);
        await queryRunner.query(`CREATE TABLE "rule_conditions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ruleId" uuid NOT NULL, "conditionType" character varying(100) NOT NULL, "fieldName" character varying(255), "operator" character varying(100), "valueJson" jsonb, "sequenceOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ff5364b054affe0bad08f1ae9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77f0ebb17bd9c95e18e4b39c6d" ON "rule_conditions" ("ruleId") `);
        await queryRunner.query(`CREATE TABLE "rule_actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ruleId" uuid NOT NULL, "actionType" character varying(100) NOT NULL, "configJson" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bb97640f29f414e475b45c90b2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_33b0c91a463427104c29965485" ON "rule_actions" ("ruleId") `);
        await queryRunner.query(`CREATE TABLE "rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "siteId" uuid, "cameraId" uuid, "name" character varying(255) NOT NULL, "description" character varying(1000), "ruleType" character varying(100) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'active', "scheduleJson" jsonb, "definitionJson" jsonb, "cooldownSeconds" integer NOT NULL DEFAULT '60', "duplicateWindowSeconds" integer NOT NULL DEFAULT '10', "severity" character varying(50) NOT NULL DEFAULT 'medium', "version" integer NOT NULL DEFAULT '1', "confidenceThreshold" numeric NOT NULL DEFAULT '0.7', "isActive" boolean NOT NULL DEFAULT true, "createdBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10fef696a7d61140361b1b23608" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0b4bf0ec875a512cad983ae207" ON "rules" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_43a5b5185fe6f34dc2f297a65e" ON "rules" ("organizationId", "siteId", "status") `);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "siteId" uuid NOT NULL, "cameraId" uuid NOT NULL, "ruleId" uuid, "zoneId" uuid, "eventType" character varying(255) NOT NULL, "severity" character varying(50) NOT NULL DEFAULT 'medium', "priority" character varying(50) NOT NULL DEFAULT 'medium', "status" character varying(50) NOT NULL DEFAULT 'new', "confidence" numeric, "description" character varying(1000), "durationSeconds" integer, "firstDetectedAt" TIMESTAMP WITH TIME ZONE, "lastDetectedAt" TIMESTAMP WITH TIME ZONE, "trackId" character varying(128), "ruleVersion" integer NOT NULL DEFAULT '1', "model" character varying(128), "modelVersion" character varying(128), "evidenceStatus" character varying(50) NOT NULL DEFAULT 'pending', "snapshotUrl" character varying(500), "videoClipUrl" character varying(500), "notes" text, "operatorNotes" text, "internalComments" text, "resolutionReason" character varying(255), "falsePositiveReason" character varying(255), "escalationReason" character varying(255), "assignedTeamId" uuid, "acknowledgedAt" TIMESTAMP WITH TIME ZONE, "investigatingAt" TIMESTAMP WITH TIME ZONE, "escalatedAt" TIMESTAMP WITH TIME ZONE, "resolvedAt" TIMESTAMP WITH TIME ZONE, "slaDueAt" TIMESTAMP WITH TIME ZONE, "slaState" character varying(20) NOT NULL DEFAULT 'on_track', "slaBreachedAt" TIMESTAMP WITH TIME ZONE, "relatedEventIds" uuid array NOT NULL DEFAULT '{}', "correlationId" character varying(100), "assignedUserId" uuid, "acknowledgedByUserId" uuid, "resolvedByUserId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e4ba026f2f893c798bda90eeaf" ON "events" ("organizationId", "status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_da41b24daa8662eef54c62e5a0" ON "events" ("eventType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d36750a840c3b031248890cf4" ON "events" ("status", "severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_401f7d0238f023f7ed9cb88515" ON "events" ("organizationId", "siteId", "cameraId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "eventId" uuid, "userId" uuid, "channel" character varying(100) NOT NULL, "priority" character varying(50) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "sentAt" TIMESTAMP, "payload" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92f5d3a7779be163cbea7916c6" ON "notifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4ab04c0b8e2d7435ec2357cce" ON "notifications" ("organizationId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "event_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventId" uuid NOT NULL, "mediaType" character varying(100) NOT NULL, "organizationId" uuid NOT NULL, "cameraId" uuid NOT NULL, "storageKey" character varying(500) NOT NULL, "storageUrl" character varying(500), "sha256" character varying(64), "byteSize" integer, "contentType" character varying(128), "width" integer, "height" integer, "durationSeconds" integer, "capturedAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, "metadataJson" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e5f0c8c1718c8c2026c15296af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f62a0e8b1f64e2809fe4769eb1" ON "event_media" ("eventId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "userId" uuid, "action" character varying(255) NOT NULL, "resourceType" character varying(100) NOT NULL, "resourceId" uuid, "ipAddress" character varying(50), "previousValueJson" jsonb, "newValueJson" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b41c13e0a4212c95088d102981" ON "audit_logs" ("resourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9885c0f9a2e4081ebae4313d87" ON "audit_logs" ("organizationId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "sites" ADD CONSTRAINT "FK_adb9781864a04730f7223964cce" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cameras" ADD CONSTRAINT "FK_ba2b06ed4823f59389e65d28cea" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cameras" ADD CONSTRAINT "FK_25b1e5f95dd486c57309f155921" FOREIGN KEY ("siteId") REFERENCES "sites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zones" ADD CONSTRAINT "FK_bbdd14f8b36385ef988d09b12c0" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zones" ADD CONSTRAINT "FK_ca8d5b97f9552e8ca9e13f9d6bb" FOREIGN KEY ("cameraId") REFERENCES "cameras"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_55fa4db8406ed66bc7044328427" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_conditions" ADD CONSTRAINT "FK_77f0ebb17bd9c95e18e4b39c6d7" FOREIGN KEY ("ruleId") REFERENCES "rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rule_actions" ADD CONSTRAINT "FK_33b0c91a463427104c299654853" FOREIGN KEY ("ruleId") REFERENCES "rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "FK_ebc3f3739911fed9b5eaf96a621" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "FK_6cf7572d3224d8e1542278f23ee" FOREIGN KEY ("siteId") REFERENCES "sites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rules" ADD CONSTRAINT "FK_f34eb8680b92b3481b7a742bc6d" FOREIGN KEY ("cameraId") REFERENCES "cameras"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_39c9cf90409495aa82f219e95d3" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_de5f36bfdc51f6ebcfeacde0020" FOREIGN KEY ("siteId") REFERENCES "sites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_0ed17b748d1a11af11f30333e82" FOREIGN KEY ("cameraId") REFERENCES "cameras"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_ca9ad089cb08845049cb8352a87" FOREIGN KEY ("ruleId") REFERENCES "rules"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_5e2493793a34cc66a92c31b1e52" FOREIGN KEY ("zoneId") REFERENCES "zones"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_1a0014fe5a2696b96cfd4056cee" FOREIGN KEY ("assignedUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_928914a0743f50e6f83a90cdda9" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_3337493bfdc5d0fccd4bd5f51e3" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_media" ADD CONSTRAINT "FK_f62a0e8b1f64e2809fe4769eb17" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_2d031e6155834882f54dcd6b4f5" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        for (const table of ['audit_logs', 'event_media', 'notifications', 'events', 'rule_actions', 'rule_conditions', 'rules', 'user_sessions', 'users', 'roles', 'zones', 'cameras', 'sites', 'organizations']) {
            await queryRunner.query(`DROP TABLE IF EXISTS "${table}" CASCADE`);
        }
    }

}
